### ISSUE TITLE
typescript: token function typings

### ISSUE THREAD

**Issue by dsvgl** [drwpow/cobalt-ui#18]
Hello, it's me again 😆 

your latest fix to https://github.com/drwpow/cobalt-ui/issues/17 doesn't work as expected.

I doesn't complains about mode as second argument needed anymore. Great.

But I don't get intellisense for mode (tested with your apple example):
<img width="835" alt="SCR-20221122-o6x" src="https://user-images.githubusercontent.com/97700093/203368597-4f62fc2b-282c-414d-a0a7-33f54731cf90.png">

Also, I can put anything in both slots:
<img width="569" alt="SCR-20221122-o79" src="https://user-images.githubusercontent.com/97700093/203368741-ee2f9842-01af-4767-a9dc-e64378f339af.png">

**Comment by drwpow** [comment]
Hello! I just fixed a TS error related to the `token()` function.

For your first problem, I’m not sure if intellisense is able to auto-fill the value. Sadly, you’ll just have to provide the value yourself, but it can tell you if the types don’t match.

For the 2nd problem—“no error”—I fixed a bug where it should throw a **type** error if you are trying to access a mode that doesn’t exist. Note that the signatures will have to match exactly, e.g.:

```ts
const mode = 'light'; // auto-cast as `string`
token('color.foreground', mode); // ❌ expecting `'light' | 'dark'`

const mode: 'light' | 'dark' = 'light';
token('color.foreground', mode); // ✅
```

In regards to **runtime errors,** however, it’s by design that this won’t throw a runtime error; it will just fall back to whatever the default value is. This is probably more generally useful, as tokens are meant to sometimes omit modes when they don’t need them.
